on:
  push:
    branches:
      - my-personal-changes

  workflow_dispatch: {}

name: Publish to GitHub Pages

jobs:
  deploy_ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: my-personal-changes

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: 'my-personal-changes/package-lock.json'

      - name: Install dependencies
        run: |
          cd my-personal-changes
          npm ci

      - name: Build
        run: |
          cd my-personal-changes
          NODE_ENV=production npm run build

      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: pages

      - name: Commit Build to gh-pages
        run: |
          cp -R my-personal-changes/dist/* pages/
          cd pages
          HAS_CHANGES=$(git diff)
          if [ -n "$HAS_CHANGES" ]; then
            git config user.name 'GH Actions Bot'
            git config user.email 'actions.bot@example.com'

            git add .
            git commit -m 'Update gh-pages site code from my-personal-changes branch'
            git push
          fi
